title: Furcsa Titkok
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
url: https://npgt.github.io
baseurl: "/wiki" # the subpath of your site, e.g. /blog

permalink: pretty

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Fel ^"

footer_content: 'Copyright &copy; 2025 npg.

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
